Repository hackbeats/python-bootcamp, pull requests merged in 2022-10, with the labels that each got.

#17 Roadmap update
  ROADMAP.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#19 Update README.md
  README.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#26 External resources
  External_Resources.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#28 Update README.md
  README.md
Labels: documentation, good first issue, no-code

#22 update
  README.md
Labels: documentation, good first issue, hacktoberfest, no-code

#31 Update guidelines and contributing mod.
  README.md
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted

#36 adding topics in python
  Python/doc.md
Labels: documentation, enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#40 add twilio quest
  External_Resources.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#34 Updated the titles of programs
  Example1.py
  Example2.py
  Example3.py
  Example4.py
  Obj_Cl.py
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#41 Update External_Resources.md
  External_Resources.md
Labels: hacktoberfest, hacktoberfest-accepted

#42 Update ROADMAP.md
  ROADMAP.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted
